name: Run Playwright test in Docker

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]


jobs:
  playwright-test:
    name: Playwright in Docker
    runs-on: ubuntu-22.04
    
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    defaults:
      run:
        working-directory: playwright_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-test/playwright-report/
          retention-days: 30
